// packages/ds-react/src/Button.tsx
import type { ComponentPropsWithoutRef, ComponentType } from 'react';
import { Button as ButtonDef, type ButtonStyleProps, type Prettify } from '@woosgem-dev/core';
import { createComponent } from './_internal/createComponent';

/**
 * Button component props.
 * Combines style props with all standard button HTML attributes,
 * while excluding protected attributes used by the design system.
 */
export type ButtonProps = Prettify<
  ButtonStyleProps &
    Omit<
      ComponentPropsWithoutRef<'button'>,
      keyof ButtonStyleProps | 'data-variant' | 'data-color' | 'data-size' | 'data-state' | 'data-full-width'
    > & {
      'data-variant'?: never;
      'data-color'?: never;
      'data-size'?: never;
      'data-state'?: never;
      'data-full-width'?: never;
    }
>;

/** Ref type for Button component */
export type ButtonRef = HTMLButtonElement;

const BaseButton = createComponent(ButtonDef, { type: 'button' });

/**
 * Button component with multiple variants, colors, and sizes.
 *
 * @example
 * ```tsx
 * <Button variant="filled" color="primary" size="md">
 *   Click me
 * </Button>
 *
 * <Button loading>Loading...</Button>
 *
 * <Button variant="outline" color="danger">
 *   Delete
 * </Button>
 * ```
 */
export const Button = BaseButton as ComponentType<ButtonProps>;

// packages/ds-lit/src/Button.ts
import { Button as ButtonCore } from '@woosgem-dev/core';
import { createComponent } from './_internal/createComponent';

/**
 * Button - Lit Web Component
 *
 * @element wg-button
 * @slot - 버튼 내용
 *
 * @example
 * ```html
 * <wg-button variant="filled" color="primary">Click me</wg-button>
 * <wg-button variant="outline" color="danger" disabled>Disabled</wg-button>
 * ```
 */
export const Button = createComponent(
  ButtonCore,
  'wg-button',
  {
    props: {
      variant: { type: String, default: 'filled' },
      color: { type: String, default: 'primary' },
      size: { type: String, default: 'md' },
      loading: { type: Boolean, default: false },
      disabled: { type: Boolean, default: false },
      fullWidth: { type: Boolean, default: false, attribute: 'full-width' },
    },
    events: {
      click: (e: MouseEvent, component) => {
        const el = component as unknown as { loading: boolean; disabled: boolean };
        if (el.loading || el.disabled) {
          e.preventDefault();
          e.stopPropagation();
        }
      },
    },
  }
);

customElements.define('wg-button', Button);

declare global {
  interface HTMLElementTagNameMap {
    'wg-button': InstanceType<typeof Button>;
  }
}
