// packages/ds-react/src/Table.tsx
import type { ComponentPropsWithoutRef, ComponentType } from 'react';
import type { Prettify } from '@woosgem-dev/core';
import {
  Table as TableDef,
  TableHead as TableHeadDef,
  TableBody as TableBodyDef,
  TableRow as TableRowDef,
  TableCell as TableCellDef,
  TableHeaderCell as TableHeaderCellDef,
  type TableStyleProps,
  type TableHeadStyleProps,
  type TableBodyStyleProps,
  type TableRowStyleProps,
  type TableCellStyleProps,
  type TableHeaderCellStyleProps,
} from '@woosgem-dev/core';
import { createComponent } from './_internal/createComponent';

// ============================================
// Table
// ============================================

export type TableProps = Prettify<
  TableStyleProps &
    Omit<
      ComponentPropsWithoutRef<'table'>,
      keyof TableStyleProps | 'data-variant' | 'data-size' | 'data-hoverable'
    > & {
      'data-variant'?: never;
      'data-size'?: never;
      'data-hoverable'?: never;
    }
>;

export type TableRef = HTMLTableElement;

/**
 * Table component for displaying tabular data.
 *
 * @example
 * ```tsx
 * <Table variant="striped" size="md" hoverable>
 *   <TableHead>
 *     <TableRow>
 *       <TableHeaderCell>Name</TableHeaderCell>
 *       <TableHeaderCell align="right">Price</TableHeaderCell>
 *     </TableRow>
 *   </TableHead>
 *   <TableBody>
 *     <TableRow>
 *       <TableCell>Item A</TableCell>
 *       <TableCell align="right">$10</TableCell>
 *     </TableRow>
 *   </TableBody>
 * </Table>
 * ```
 */
export const Table = createComponent(TableDef, {}) as ComponentType<TableProps>;

// ============================================
// TableHead
// ============================================

export type TableHeadProps = Prettify<TableHeadStyleProps & ComponentPropsWithoutRef<'thead'>>;

export type TableHeadRef = HTMLTableSectionElement;

/**
 * Table head section.
 */
export const TableHead = createComponent(TableHeadDef, {}) as ComponentType<TableHeadProps>;

// ============================================
// TableBody
// ============================================

export type TableBodyProps = Prettify<TableBodyStyleProps & ComponentPropsWithoutRef<'tbody'>>;

export type TableBodyRef = HTMLTableSectionElement;

/**
 * Table body section.
 */
export const TableBody = createComponent(TableBodyDef, {}) as ComponentType<TableBodyProps>;

// ============================================
// TableRow
// ============================================

export type TableRowProps = Prettify<
  TableRowStyleProps &
    Omit<
      ComponentPropsWithoutRef<'tr'>,
      keyof TableRowStyleProps | 'data-state' | 'aria-selected'
    > & {
      'data-state'?: never;
      'aria-selected'?: never;
    }
>;

export type TableRowRef = HTMLTableRowElement;

/**
 * Table row with optional selected state.
 */
export const TableRow = createComponent(TableRowDef, {}) as ComponentType<TableRowProps>;

// ============================================
// TableCell
// ============================================

export type TableCellProps = Prettify<
  TableCellStyleProps &
    Omit<ComponentPropsWithoutRef<'td'>, keyof TableCellStyleProps | 'data-align'> & {
      'data-align'?: never;
    }
>;

export type TableCellRef = HTMLTableCellElement;

/**
 * Table data cell with optional alignment.
 */
export const TableCell = createComponent(TableCellDef, {}) as ComponentType<TableCellProps>;

// ============================================
// TableHeaderCell
// ============================================

export type TableHeaderCellProps = Prettify<
  TableHeaderCellStyleProps &
    Omit<
      ComponentPropsWithoutRef<'th'>,
      keyof TableHeaderCellStyleProps | 'data-align' | 'data-sortable' | 'scope'
    > & {
      'data-align'?: never;
      'data-sortable'?: never;
      scope?: never;
    }
>;

export type TableHeaderCellRef = HTMLTableCellElement;

/**
 * Table header cell with optional alignment and sortable indicator.
 */
export const TableHeaderCell = createComponent(TableHeaderCellDef, {}) as ComponentType<TableHeaderCellProps>;

// packages/ds-lit/src/Table.ts
import {
  Table as TableCore,
  TableHead as TableHeadCore,
  TableBody as TableBodyCore,
  TableRow as TableRowCore,
  TableCell as TableCellCore,
  TableHeaderCell as TableHeaderCellCore,
} from '@woosgem-dev/core';
import { createComponent } from './_internal/createComponent';

/**
 * Table - Lit Web Component
 *
 * @element wg-table
 * @slot - Table content (thead, tbody)
 *
 * @example
 * ```html
 * <wg-table variant="striped" size="md" hoverable>
 *   <wg-table-head>
 *     <wg-table-row>
 *       <wg-table-header-cell>Name</wg-table-header-cell>
 *     </wg-table-row>
 *   </wg-table-head>
 *   <wg-table-body>
 *     <wg-table-row>
 *       <wg-table-cell>Item A</wg-table-cell>
 *     </wg-table-row>
 *   </wg-table-body>
 * </wg-table>
 * ```
 */
export const Table = createComponent(
  TableCore,
  'wg-table',
  {
    props: {
      variant: { type: String, default: 'default' },
      size: { type: String, default: 'md' },
      hoverable: { type: Boolean, default: false },
    },
  }
);

customElements.define('wg-table', Table);

/**
 * TableHead - Lit Web Component
 *
 * @element wg-table-head
 * @slot - Header rows
 */
export const TableHead = createComponent(
  TableHeadCore,
  'wg-table-head',
  {
    props: {},
  }
);

customElements.define('wg-table-head', TableHead);

/**
 * TableBody - Lit Web Component
 *
 * @element wg-table-body
 * @slot - Body rows
 */
export const TableBody = createComponent(
  TableBodyCore,
  'wg-table-body',
  {
    props: {},
  }
);

customElements.define('wg-table-body', TableBody);

/**
 * TableRow - Lit Web Component
 *
 * @element wg-table-row
 * @slot - Row cells
 */
export const TableRow = createComponent(
  TableRowCore,
  'wg-table-row',
  {
    props: {
      selected: { type: Boolean, default: false },
    },
  }
);

customElements.define('wg-table-row', TableRow);

/**
 * TableCell - Lit Web Component
 *
 * @element wg-table-cell
 * @slot - Cell content
 */
export const TableCell = createComponent(
  TableCellCore,
  'wg-table-cell',
  {
    props: {
      align: { type: String, default: 'left' },
    },
  }
);

customElements.define('wg-table-cell', TableCell);

/**
 * TableHeaderCell - Lit Web Component
 *
 * @element wg-table-header-cell
 * @slot - Header cell content
 */
export const TableHeaderCell = createComponent(
  TableHeaderCellCore,
  'wg-table-header-cell',
  {
    props: {
      align: { type: String, default: 'left' },
      sortable: { type: Boolean, default: false },
    },
  }
);

customElements.define('wg-table-header-cell', TableHeaderCell);

declare global {
  interface HTMLElementTagNameMap {
    'wg-table': InstanceType<typeof Table>;
    'wg-table-head': InstanceType<typeof TableHead>;
    'wg-table-body': InstanceType<typeof TableBody>;
    'wg-table-row': InstanceType<typeof TableRow>;
    'wg-table-cell': InstanceType<typeof TableCell>;
    'wg-table-header-cell': InstanceType<typeof TableHeaderCell>;
  }
}
