// packages/ds-lit/src/Kbd.ts
import { Kbd as KbdCore } from '@woosgem-dev/core';
import { createComponent } from './_internal/createComponent';

/**
 * Kbd - Lit Web Component
 *
 * Keyboard key indicator for displaying keyboard shortcuts.
 *
 * @element wg-kbd
 * @slot - Key label content
 *
 * @example
 * ```html
 * <wg-kbd>Ctrl</wg-kbd>
 * <wg-kbd variant="flat" size="md">Enter</wg-kbd>
 * ```
 */
export const Kbd = createComponent(
  KbdCore,
  'wg-kbd',
  {
    props: {
      size: { type: String, default: 'sm' },
      variant: { type: String, default: 'raised' },
    },
  }
);

customElements.define('wg-kbd', Kbd);

declare global {
  interface HTMLElementTagNameMap {
    'wg-kbd': InstanceType<typeof Kbd>;
  }
}

// packages/ds-react/src/Kbd.tsx
import type { ComponentPropsWithoutRef, ComponentType } from 'react';
import { Kbd as KbdDef, type KbdStyleProps, type Prettify } from '@woosgem-dev/core';
import { createComponent } from './_internal/createComponent';

/**
 * Kbd component props.
 * Combines style props with all standard kbd HTML attributes.
 */
export type KbdProps = Prettify<
  KbdStyleProps &
    Omit<
      ComponentPropsWithoutRef<'kbd'>,
      keyof KbdStyleProps | 'data-size' | 'data-variant'
    > & {
      'data-size'?: never;
      'data-variant'?: never;
    }
>;

/** Ref type for Kbd component */
export type KbdRef = HTMLElement;

const BaseKbd = createComponent(KbdDef, {});

/**
 * Kbd component for displaying keyboard shortcuts.
 *
 * @example
 * ```tsx
 * <Kbd>⌘K</Kbd>
 * <Kbd size="md" variant="flat">Ctrl</Kbd>
 * <Kbd>Enter</Kbd>
 * ```
 */
export const Kbd = BaseKbd as ComponentType<KbdProps>;
