// packages/ds-lit/src/Spinner.ts
import { Spinner as SpinnerCore } from '@woosgem-dev/core';
import { createComponent } from './_internal/createComponent';

/**
 * Spinner - Lit Web Component
 *
 * @element wg-spinner
 *
 * @example
 * ```html
 * <wg-spinner size="md" color="primary"></wg-spinner>
 * <wg-spinner size="lg" color="secondary" label="Loading data..."></wg-spinner>
 * ```
 */
export const Spinner = createComponent(
  SpinnerCore,
  'wg-spinner',
  {
    props: {
      size: { type: String, default: 'md' },
      color: { type: String, default: 'primary' },
      label: { type: String, default: 'Loading...' },
    },
  }
);

customElements.define('wg-spinner', Spinner);

declare global {
  interface HTMLElementTagNameMap {
    'wg-spinner': InstanceType<typeof Spinner>;
  }
}

// packages/ds-react/src/Spinner.tsx
import type { ComponentPropsWithoutRef, ComponentType } from 'react';
import { Spinner as SpinnerDef, type SpinnerStyleProps, type Prettify } from '@woosgem-dev/core';
import { createComponent } from './_internal/createComponent';

/**
 * Spinner component props.
 * Combines style props with all standard div HTML attributes,
 * while excluding protected attributes used by the design system.
 */
export type SpinnerProps = Prettify<
  SpinnerStyleProps &
    Omit<ComponentPropsWithoutRef<'div'>, keyof SpinnerStyleProps | 'data-size' | 'data-color' | 'role'> & {
      'data-size'?: never;
      'data-color'?: never;
      role?: never;
    }
>;

/** Ref type for Spinner component */
export type SpinnerRef = HTMLDivElement;

const BaseSpinner = createComponent(SpinnerDef);

/**
 * Spinner component for loading states.
 *
 * @example
 * ```tsx
 * <Spinner />
 *
 * <Spinner size="lg" color="secondary" />
 *
 * <Spinner label="데이터를 불러오는 중..." />
 * ```
 */
export const Spinner = BaseSpinner as ComponentType<SpinnerProps>;
