// packages/ds-lit/src/Tooltip.ts
import { LitElement, html, type TemplateResult } from 'lit';
import { property, state } from 'lit/decorators.js';
import {
  Tooltip as TooltipCore,
  type TooltipPosition,
  type TooltipTrigger,
} from '@woosgem-dev/core';
import { applyAttrsToElement } from './_internal/createComponent';

let tooltipIdCounter = 0;

/**
 * Tooltip - Lit Web Component
 *
 * @element wg-tooltip
 * @slot - Trigger element
 *
 * @example
 * ```html
 * <wg-tooltip content="This is a tooltip">
 *   <button>Hover me</button>
 * </wg-tooltip>
 *
 * <wg-tooltip content="Click tooltip" trigger="click" position="bottom">
 *   <button>Click me</button>
 * </wg-tooltip>
 * ```
 */
export class Tooltip extends LitElement {
  static properties = {
    content: { type: String },
    position: { type: String },
    trigger: { type: String },
    delay: { type: Number },
    arrow: { type: Boolean },
    visible: { type: Boolean },
    disabled: { type: Boolean },
  };

  @property({ type: String }) content = '';
  @property({ type: String }) position: TooltipPosition = 'top';
  @property({ type: String }) trigger: TooltipTrigger = 'hover';
  @property({ type: Number }) delay = 0;
  @property({ type: Boolean }) arrow = true;
  @property({ type: Boolean }) visible = false;
  @property({ type: Boolean }) disabled = false;

  @state() private _internalVisible = false;

  private _timeoutId: number | null = null;
  private _tooltipId = `wg-tooltip-${++tooltipIdCounter}`;

  // Light DOM for ds-styles compatibility
  createRenderRoot(): HTMLElement {
    return this;
  }

  private get _isVisible(): boolean {
    return this.visible || this._internalVisible;
  }

  private _showTooltip = (): void => {
    if (this.disabled) return;
    if (this.delay > 0) {
      this._timeoutId = window.setTimeout(() => {
        this._internalVisible = true;
        this._emitVisibleChange(true);
      }, this.delay);
    } else {
      this._internalVisible = true;
      this._emitVisibleChange(true);
    }
  };

  private _hideTooltip = (): void => {
    if (this._timeoutId) {
      clearTimeout(this._timeoutId);
      this._timeoutId = null;
    }
    this._internalVisible = false;
    this._emitVisibleChange(false);
  };

  private _toggleTooltip = (): void => {
    if (this.disabled) return;
    this._internalVisible = !this._internalVisible;
    this._emitVisibleChange(this._internalVisible);
  };

  private _emitVisibleChange(visible: boolean): void {
    this.dispatchEvent(
      new CustomEvent('visible-change', {
        bubbles: true,
        composed: true,
        detail: { visible },
      })
    );
  }

  disconnectedCallback(): void {
    super.disconnectedCallback();
    if (this._timeoutId) {
      clearTimeout(this._timeoutId);
    }
  }

  updated(): void {
    this._applyWrapperAttrs();
  }

  connectedCallback(): void {
    super.connectedCallback();
    this._applyWrapperAttrs();
  }

  private _applyWrapperAttrs(): void {
    this.classList.add('wg-tooltip-wrapper');
    this.setAttribute('data-position', this.position);
  }

  render(): TemplateResult {
    const attrs = TooltipCore.mapPropsToAttrs({
      content: this.content,
      position: this.position,
      trigger: this.trigger,
      delay: this.delay,
      arrow: this.arrow,
      visible: this._isVisible,
      disabled: this.disabled,
    });

    // Build trigger handlers based on trigger type
    const triggerHandlers =
      this.trigger === 'hover'
        ? {
            '@mouseenter': this._showTooltip,
            '@mouseleave': this._hideTooltip,
          }
        : this.trigger === 'focus'
          ? {
              '@focus': this._showTooltip,
              '@blur': this._hideTooltip,
            }
          : this.trigger === 'click'
            ? {
                '@click': this._toggleTooltip,
              }
            : {};

    return html`
      <span
        class="wg-tooltip__trigger"
        aria-describedby=${this._isVisible ? this._tooltipId : ''}
        @mouseenter=${this.trigger === 'hover' ? this._showTooltip : undefined}
        @mouseleave=${this.trigger === 'hover' ? this._hideTooltip : undefined}
        @focus=${this.trigger === 'focus' ? this._showTooltip : undefined}
        @blur=${this.trigger === 'focus' ? this._hideTooltip : undefined}
        @click=${this.trigger === 'click' ? this._toggleTooltip : undefined}
      >
        <slot></slot>
      </span>

      <div
        id=${this._tooltipId}
        class=${attrs.class}
        data-position=${attrs['data-position']}
        data-trigger=${attrs['data-trigger']}
        ?data-arrow=${attrs['data-arrow']}
        ?data-visible=${attrs['data-visible']}
        ?data-disabled=${attrs['data-disabled']}
        role=${attrs.role}
        aria-hidden=${!this._isVisible}
      >
        ${this.arrow ? html`<span class="wg-tooltip__arrow"></span>` : ''}
        <span class="wg-tooltip__content">${this.content}</span>
      </div>
    `;
  }
}

customElements.define('wg-tooltip', Tooltip);

declare global {
  interface HTMLElementTagNameMap {
    'wg-tooltip': Tooltip;
  }
}

// packages/ds-react/src/Tooltip.tsx
import {
  forwardRef,
  memo,
  useState,
  useCallback,
  useRef,
  useEffect,
  type ReactNode,
  type ComponentPropsWithoutRef,
  type ComponentType,
} from 'react';
import {
  Tooltip as TooltipDef,
  type TooltipStyleProps,
  type Prettify,
} from '@woosgem-dev/core';
import { useId } from './_internal/useId';

/**
 * Tooltip component props.
 * Combines style props with all standard div HTML attributes,
 * while excluding protected attributes used by the design system.
 */
export type TooltipProps = Prettify<
  TooltipStyleProps &
    Omit<
      ComponentPropsWithoutRef<'div'>,
      | keyof TooltipStyleProps
      | 'data-position'
      | 'data-trigger'
      | 'data-arrow'
      | 'data-visible'
      | 'data-disabled'
      | 'role'
    > & {
      /** Children to wrap with tooltip */
      children: ReactNode;
      'data-position'?: never;
      'data-trigger'?: never;
      'data-arrow'?: never;
      'data-visible'?: never;
      'data-disabled'?: never;
    }
>;

/** Ref type for Tooltip component */
export type TooltipRef = HTMLDivElement;

/**
 * Tooltip component for displaying additional information on hover, focus, or click.
 *
 * @example
 * ```tsx
 * <Tooltip content="This is a tooltip">
 *   <Button>Hover me</Button>
 * </Tooltip>
 *
 * <Tooltip content="Click to see" trigger="click" position="bottom">
 *   <IconButton icon="info" />
 * </Tooltip>
 *
 * <Tooltip content="Focus tooltip" trigger="focus" arrow={false}>
 *   <Input placeholder="Focus me" />
 * </Tooltip>
 * ```
 */
const TooltipBase = forwardRef<TooltipRef, TooltipProps>(function Tooltip(
  {
    children,
    content = '',
    position = 'top',
    trigger = 'hover',
    delay = 0,
    arrow = true,
    visible: controlledVisible,
    disabled = false,
    className,
    ...restProps
  },
  ref
) {
  const [internalVisible, setInternalVisible] = useState(false);
  const timeoutRef = useRef<number | null>(null);
  const tooltipId = useId('tooltip');

  // Use controlled visible if provided, otherwise use internal state
  const isControlled = controlledVisible !== undefined;
  const isVisible = isControlled ? controlledVisible : internalVisible;

  const showTooltip = useCallback(() => {
    if (disabled) return;
    if (delay > 0) {
      timeoutRef.current = window.setTimeout(() => {
        setInternalVisible(true);
      }, delay);
    } else {
      setInternalVisible(true);
    }
  }, [disabled, delay]);

  const hideTooltip = useCallback(() => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
      timeoutRef.current = null;
    }
    setInternalVisible(false);
  }, []);

  const toggleTooltip = useCallback(() => {
    if (disabled) return;
    setInternalVisible((prev) => !prev);
  }, [disabled]);

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }
    };
  }, []);

  // Get attrs from Core definition
  const attrs = TooltipDef.mapPropsToAttrs({
    content,
    position,
    trigger,
    delay,
    arrow,
    visible: isVisible,
    disabled,
  });

  // Build trigger handlers based on trigger type
  const triggerHandlers =
    trigger === 'hover'
      ? {
          onMouseEnter: showTooltip,
          onMouseLeave: hideTooltip,
        }
      : trigger === 'focus'
        ? {
            onFocus: showTooltip,
            onBlur: hideTooltip,
          }
        : trigger === 'click'
          ? {
              onClick: toggleTooltip,
            }
          : {};

  const finalClassName = className ? `wg-tooltip-wrapper ${className}` : 'wg-tooltip-wrapper';

  return (
    <div
      ref={ref}
      className={finalClassName}
      data-position={position}
      {...triggerHandlers}
      {...restProps}
    >
      {/* Trigger element with aria-describedby */}
      <span className="wg-tooltip__trigger" aria-describedby={isVisible ? tooltipId : undefined}>
        {children}
      </span>

      {/* Tooltip content */}
      <div
        id={tooltipId}
        className={attrs.class}
        data-position={attrs['data-position']}
        data-trigger={attrs['data-trigger']}
        data-arrow={attrs['data-arrow']}
        data-visible={attrs['data-visible']}
        data-disabled={attrs['data-disabled']}
        role={attrs.role}
        aria-hidden={!isVisible}
      >
        {arrow && <span className="wg-tooltip__arrow" />}
        <span className="wg-tooltip__content">{content}</span>
      </div>
    </div>
  );
});

TooltipBase.displayName = 'Tooltip';

export const Tooltip = memo(TooltipBase) as ComponentType<TooltipProps>;
